app = "openmesh"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3777
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[env]
  NODE_ENV = "production"
  OPENMESH_DASHBOARD_PORT = "3777"
