apiVersion: v1
kind: Service
metadata:
  name: {{ include "openmesh.fullname" . }}
  labels:
    {{- include "openmesh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.dashboard.enabled }}
    - port: {{ .Values.service.port }}
      targetPort: dashboard
      protocol: TCP
      name: dashboard
    {{- end }}
    {{- if .Values.mcp.enabled }}
    - port: {{ .Values.mcp.port }}
      targetPort: mcp
      protocol: TCP
      name: mcp
    {{- end }}
    {{- if .Values.prometheus.enabled }}
    - port: {{ .Values.prometheus.port }}
      targetPort: {{ .Values.prometheus.port }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "openmesh.selectorLabels" . | nindent 4 }}
